---
- name: Ensure nexus service is created and running
  hosts: ansibt0
  vars_files: ../vars.yaml
  tasks:

    - name: Ensure nexus.service file is present on systemd directory
      ansible.builtin.template:
        src: "{{ root.directory }}/template/nexus.service.j2"
        dest: /usr/lib/systemd/system/nexus.service
        owner: nexus
        group: nexus

    - name: Ensure nexus.service is enable
      ansible.builtin.systemd_service:
        name: nexus.service
        daemon_reload: true
        enabled: true
        state: started
